#!/bin/bash

# Hide "last login" line when starting a new terminal session
touch $HOME/.hushlogin

# Install zsh
echo 'Install oh-my-zsh'
echo '-----------------'
rm -rf $HOME/.oh-my-zsh
curl -L https://raw.githubusercontent.com/ohmyzsh/oh-my-zsh/master/tools/install.sh | sh

# Add global gitignore
ln -s $HOME/.dotfiles/shell/.global-gitignore $HOME/.global-gitignore
git config --global core.excludesfile $HOME/.global-gitignore

# Symlink zsh prefs
rm $HOME/.zshrc
ln -s $HOME/.dotfiles/shell/.zshrc $HOME/.zshrc

# Symlink vim prefs
rm $HOME/.vimrc
ln -s $HOME/.dotfiles/shell/.vimrc $HOME/.vimrc
rm $HOME/.vim
ln -s $HOME/.dotfiles/shell/.vim $HOME/.vim

# Symlink the Mackup config
# ln -s $HOME/.dotfiles/macos/.mackup.cfg $HOME/.mackup.cfg

# Fix missing font characters (see https://github.com/ohmyzsh/ohmyzsh/issues/1906)
#cd ~/.oh-my-zsh/themes/
#git checkout d6a36b1 agnoster.zsh-theme

# Activate z
cd ~/.dotfiles/shell
chmod +x z.sh

echo 'Install homebrew'
echo '----------------'
echo install homebrew
sudo rm -rf /usr/local/Cellar /usr/local/.git && brew cleanup
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> $HOME/.zprofile
eval "$(/opt/homebrew/bin/brew shellenv)"

echo '==================================='
echo 'DEVELOPMENT TOOLS'
echo '==================================='

echo 'Install node'
echo '------------'
brew install node

echo 'Configure npm'
echo '-------------'
# Create a directory for global packages and tell npm where to store globally installed packages
mkdir "${HOME}/.npm-packages"
npm config set prefix "${HOME}/.npm-packages"

echo 'Install pkg-config'
echo '------------------'
brew install pkg-config

echo 'Install GitHub CLI'
echo '------------------'
brew install gh

echo 'Install HTTPie (HTTP client)'
echo '----------------------------'
brew install httpie

echo 'Install doctl (DigitalOcean CLI)'
echo '--------------------------------'
brew install doctl

echo 'Install Supabase CLI'
echo '--------------------'
brew install supabase

echo 'Install ngrok'
echo '--------------'
brew install ngrok

echo 'Install watchman'
echo '----------------'
brew install watchman

echo 'Install uv (Python package manager)'
echo '------------------------------------'
brew install uv

echo 'Install composer'
echo '----------------'
brew install composer

#echo 'Install PHP 8.4'
#echo '---------------'
#brew install php@8.4

echo 'Install pie (PHP extension installer)'
echo '-------------------------------------'
brew install pie

echo 'Install micro (terminal text editor)'
echo '------------------------------------'
brew install micro

echo 'Install pandoc (document converter)'
echo '-----------------------------------'
brew install pandoc

echo '==================================='
echo 'SYSTEM UTILITIES'
echo '==================================='

echo 'Install wget'
echo '------------'
brew install wget

echo 'Install ncdu (NCurses Disk Usage)'
echo '------------'
brew install ncdu

echo 'Install ack (grep alternative)'
echo '-----------'
brew install ack

echo 'Install typos-cli (codebase spell checker)'
echo '-----------------'
brew install typos-cli

echo 'Install gping (visual ping)'
echo '---------------------------'
brew install gping

echo 'Install htop (system monitor)'
echo '-----------------------------'
brew install htop

echo 'Install mtr (network diagnostic)'
echo '--------------------------------'
brew install mtr

echo 'Install bat (cat with syntax highlighting)'
echo '------------------------------------------'
brew install bat

echo 'Install zsh-autosuggestions'
echo '---------------------------'
brew install zsh-autosuggestions

echo '==================================='
echo 'MULTIMEDIA TOOLS'
echo '==================================='

echo 'Install ffmpeg'
echo '--------------'
brew install ffmpeg

echo 'Install yt-dlp (video downloader)'
echo '--------------'
brew install yt-dlp

echo '==================================='
echo 'PRODUCTIVITY APPS'
echo '==================================='

echo 'Install Warp Terminal'
echo '---------------------'
brew install --cask warp

echo 'Install Raycast'
echo '---------------'
brew install --cask raycast

echo 'Install Sublime Text'
echo '--------------------'
brew install --cask sublime-text
# https://stackoverflow.com/questions/16199581/open-sublime-text-from-terminal-in-macos
sudo ln -s /Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl /usr/local/bin/subl

echo 'Install git secret'
echo '------------------'
brew install git-secret

echo '==================================='
echo 'DEVELOPMENT APPS'
echo '==================================='

echo 'Install Docker Desktop'
echo '----------------------'
brew install --cask docker-desktop

echo 'Install LM Studio (AI)'
echo '----------------------'
brew install --cask lm-studio

echo 'Install JetBrains Toolbox'
echo '-------------------------'
brew install --cask jetbrains-toolbox

echo '==================================='
echo 'PRODUCTIVITY & UTILITIES'
echo '==================================='

echo 'Install Obsidian'
echo '----------------'
brew install --cask obsidian

echo 'Install Dropbox'
echo '---------------'
brew install --cask dropbox

echo 'Install disk-inventory-x'
echo '-----------------------'
brew install --cask disk-inventory-x

echo 'Install Shottr (screenshots)'
echo '----------------------------'
brew install --cask shottr

echo 'Install GPG Suite'
echo '-----------------'
brew install --cask gpg-suite

echo 'Install pinentry-mac (for GPG)'
echo '--------------------'
brew install pinentry-mac

echo 'Install Hubstaff (time tracking)'
echo '--------------------------------'
brew install --cask hubstaff

echo 'Install Loom (screen recording)'
echo '-------------------------------'
brew install --cask loom

echo '==================================='
echo 'MULTIMEDIA APPS'
echo '==================================='

echo 'Install VLC'
echo '-----------'
brew install --cask vlc

echo 'Install foobar2000'
echo '------------------'
brew install --cask foobar2000

echo 'Install Spotify'
echo '---------------'
brew install --cask spotify

echo 'Install Soulseek'
echo '----------------'
brew install --cask soulseek

echo '==================================='
echo 'INTERNET & COMMUNICATION'
echo '==================================='

echo 'Install Firefox'
echo '---------------'
brew install --cask firefox

echo 'Install Zoom'
echo '-------------'
brew install --cask zoom

echo 'Install Transmission'
echo '--------------------'
brew install --cask transmission

echo '==================================='
echo 'SECURITY & SYSTEM'
echo '==================================='

echo 'Install LuLu (firewall)'
echo '-----------------------'
brew install --cask lulu

echo '==================================='
echo 'QUICKLOOK PLUGINS & UTILITIES'
echo '==================================='

echo 'Install QuickLook plugins'
echo '-------------------------'
brew install --cask \
  qlcolorcode \        # Preview source code files with syntax highlighting
  qlstephen \          # Preview plain text files without extensions
  qlmarkdown \         # Preview Markdown files
  quicklook-json \     # Preview JSON files
  qlprettypatch \      # Preview patch files
  quicklook-csv \      # Preview CSV files
  betterzip \          # Preview archive contents
  syntax-highlight \   # Enhanced syntax highlighting for various file types
  suspicious-package   # Preview package contents

echo 'Install php'
echo '-----------'
brew tap shivammathur/php
brew install shivammathur/php/php@8.4
brew link --overwrite --force php@8.4

echo 'Install cpx'
composer global require cpx/cpx

#echo 'Install imagemagick'
#echo '-------------------'
#brew install imagemagick

#echo 'Install imagick'
#echo '---------------'
#pecl install imagick

#echo 'Install memcached'
#echo '-----------------'
#pecl install memcached

echo 'Install xdebug'
echo '--------------'
pie install xdebug/xdebug

echo 'Install phpredis'
echo '-------------'
pie install phpredis/phpredis

#echo 'Install laravel envoy'
#echo '---------------------'
#composer global require "laravel/envoy=~2.0"

#echo 'Install phpunit-watcher'
#echo '-----------------------'
#composer global require spatie/phpunit-watcher

#echo 'Install laravel valet'
#echo '---------------------'
#composer global require laravel/valet
#valet install

#echo 'Install mysql'
#echo '-------------'
#brew install mysql
#brew services start mysql

echo 'Install yarn'
echo '------------'
brew install yarn

#echo 'Install ghostscript'
#echo '-------------------'
#brew install ghostscript

#echo 'Install mackup'
#echo '--------------'
#brew install mackup

echo '++++++++++++++++++++++++++++++'
echo '++++++++++++++++++++++++++++++'
echo 'All done!'
echo 'Things to do to make the agnoster terminal theme work:'
echo '1. Install menlo patched font included in ~/.dotfiles/misc https://gist.github.com/qrush/1595572/raw/Menlo-Powerline.otf'
echo '2. Install patched solarized theme included in ~/.dotfiles/misc, see https://apple.stackexchange.com/questions/27878/how-can-i-install-themes-for-terminal'

echo '++++++++++++++++++++++++++++++'
echo 'Some optional tidbits'

echo '1. Make sure dropbox is running first. If you have not backed up via Mackup yet, then run `mackup backup` to symlink preferences for a wide collection of apps to your dropbox. If you already had a backup via mackup run `mackup restore` You’ll find more info on Mackup here: https://github.com/lra/mackup.'
echo '2. Set some sensible os x defaults by running: $HOME/.dotfiles/macos/set-defaults.sh'
echo '3. Make a .dotfiles-custom/shell/.aliases for your personal commands'

echo '++++++++++++++++++++++++++++++'
echo '++++++++++++++++++++++++++++++'
